name: Bot Test
on:
  push:
    branches: [ master ]

jobs:
  bot-1:
    runs-on: self-hosted
    name: Bot Test 1
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test
        run: echo "First test conect with runner"
